name: Build linuxOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc libcriterion-dev pkg-config

      # 读取版本信息
      - name: Read version from JSON
        id: version
        run: |
          PROJECT=$(jq -r '.name' dytes.json)
          VERSION=$(jq -r '.version' dytes.json)
          echo "project=$PROJECT" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=ON

      - name: Build
        run: |
          cd build
          make -j4

      - name: Run tests
        run: |
          cd build
          ./cyctron_tests

      - name: Upload to UpYun S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.UPYUN_API_KEY }}
          aws_secret_access_key: ${{ secrets.UPYUN_API_SECRET }}
          aws_bucket: ${{ secrets.UPYUN_BUCKET }}
          source_dir: './build/cyctron'
          destination_dir: '/core/${{ steps.version.outputs.project }}/${{ steps.version.outputs.version }}/linux'
          endpoint: 'https://s3.api.upyun.com'

